### ISSUE TITLE
Conditional Field Key possible? 

### ISSUE THREAD

**Issue by Henryvart** [Hube2/acf-filters-and-functions#11]
I have a dog family tree I'm building and this code works great!

A child can choose a mother or father and that exchange of data works great. The tricky part is when a parent chooses a child. The parent will show up on both the mother and father fields. Is there anyway to maybe choose a different field key depending on the gender of the parent? 

For example, if the parent's gender is male then the field key is 'father field key' else field key is 'mother field  key'

essentially there are three fields involved. 
dog_father
dog_mother
dog_child

On the child profile selecting a father and mother is no problem. 
On the parent profile selecting a child will put the parent on both dog_father and dog_mother field because I have a filter for both those fields have a bidirectional relationship with dog_child. 

I want to be able to determine how I can target dog_father if the gender (another custom field) is male and dog_mother if gender is female. 

Is something like this possible with your code?

**Comment by Henryvart** [comment]
I'll close. I was able to solve by adding 3 filters and making one of the keys conditional depending on the  value of another custom field. Thank you again.

**Comment by Hube2** [comment]
I would probably have 2 different relationships, one for father/child and one for mother/child. But I'm glad you got it worked out.
