### ISSUE TITLE
acf-image-aspect-ratio-validation.php shows notice errors

### ISSUE THREAD

**Issue by tmconnect** [Hube2/acf-filters-and-functions#3]
I put this into my functions.php and after that I got the notice two times if I have set WP_DEBUG to true

`Undefined index: class in /wordpress/wp-content/plugins/advanced-custom-fields-pro/acf/api/api-field.php on line 579`

**Comment by Hube2** [comment]
I think that should fix the issue, let me know

**Comment by tmconnect** [comment]
Yes, thank you!
